import { env } from '@/config/env';

export const API_BASE_URL = env.API_BASE_URL;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    OTP_SEND: '/auth/otp/send',
    OTP_VERIFY: '/auth/otp/verify',
    SET_PASSWORD: '/auth/set-password',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    ME_UPDATE: '/auth/me',
    ME_AVATAR: '/auth/me/avatar',
  },
  DEALER: {
    REGISTER: '/register/dealer',
    PROFILE: '/dealer/profile',
  },
  CUSTOMER: {
    REGISTER: '/register/customer',
    ADDRESSES: '/customer/addresses',
    ADDRESS_DETAIL: (id: string) => `/customer/addresses/${id}`,
    ADDRESS_DEFAULT: (id: string) => `/customer/addresses/${id}/default`,
  },
  CATALOGUE: {
    PRODUCTS: '/catalogue/products',
    PRODUCT_DETAIL: (id: string | number) => `/catalogue/products/${id}`,
    PRODUCT_VARIANTS: (id: string | number) => `/catalogue/products/${id}/variants`,
    VARIANT_DETAIL: (variantId: string | number) => `/catalogue/variants/${variantId}`,
  },
  CART: {
    GET: '/cart',
    ADD_ITEM: '/cart/items',
    UPDATE_ITEM: (variantId: string | number) => `/cart/items/${variantId}`,
    REMOVE_ITEM: (variantId: string | number) => `/cart/items/${variantId}`,
    CLEAR: '/cart',
    SET_ADDRESS: '/cart/address',
    SET_COUPON: '/cart/coupon',
    REMOVE_COUPON: '/cart/coupon',
    CHECKOUT: '/cart/checkout',
  },
  WISHLIST: {
    GET: '/wishlist',
    ADD_ITEM: '/wishlist/items',
    REMOVE_ITEM: (variantId: string | number) => `/wishlist/items/${variantId}`,
    CLEAR: '/wishlist',
    MOVE_TO_CART: (variantId: string | number) => `/wishlist/items/${variantId}/move-to-cart`,
  },
  COUPONS: {
    VALIDATE: (code: string, orderTotal: number) =>
      `/coupons/validate?code=${encodeURIComponent(code)}&order_total=${orderTotal}`,
  },
  ORDERS: {
    CREATE: '/orders',
    DEALER: {
      LIST: '/dealer/orders',
      DETAIL: (id: string) => `/dealer/orders/${id}`,
      CONFIRM_DELIVERY: (id: string) => `/dealer/orders/${id}/confirm-delivery`,
      CANCEL: (id: string) => `/dealer/orders/${id}/cancel`,
    },
    CUSTOMER: {
      LIST: '/customer/orders',
      DETAIL: (id: string) => `/customer/orders/${id}`,
      CONFIRM_DELIVERY: (id: string) => `/customer/orders/${id}/confirm-delivery`,
      CANCEL: (id: string) => `/customer/orders/${id}/cancel`,
    },
  },
  PAYMENTS: {
    INITIATE_GATEWAY: '/payments/gateway/initiate',
    VERIFY_GATEWAY: '/payments/gateway/verify',
    UPLOAD_MANUAL: '/payments/manual/upload',
    INITIATE_BOOKING_GATEWAY: (bookingId: string) => `/service/bookings/${bookingId}/payment/initiate-gateway`,
  },
  QUOTES: {
    LIST: '/quotes',
    DETAIL: (id: string) => `/quotes/${id}`,
    PDF: (id: string) => `/quotes/${id}/pdf`,
    ACCEPT: (id: string) => `/quotes/${id}/accept`,
    REJECT: (id: string) => `/quotes/${id}/reject`,
  },
  RETURNS: {
    CREATE: (orderId: string) => `/orders/${orderId}/returns`,
    UPLOAD_EVIDENCE: '/returns/upload-evidence',
    DEALER_LIST: '/dealer/returns',
    DEALER_DETAIL: (id: string) => `/dealer/returns/${id}`,
    DEALER_CREDIT_NOTE_DOWNLOAD: (returnId: string) => `/dealer/returns/${returnId}/credit-note/download`,
    CUSTOMER_LIST: '/customer/returns',
    CUSTOMER_DETAIL: (id: string) => `/customer/returns/${id}`,
    CUSTOMER_CREDIT_NOTE_DOWNLOAD: (returnId: string) => `/customer/returns/${returnId}/credit-note/download`,
  },
  SERVICES: {
    CATALOGUE: '/service/catalogue',
    BOOKINGS_CREATE: '/service/bookings',
    BOOKINGS_LIST: '/service/bookings',
    BOOKING_DETAIL: (id: string) => `/service/bookings/${id}`,
    BOOKING_CANCEL: (id: string) => `/service/bookings/${id}/cancel`,
    BOOKING_PAYMENT: (id: string) => `/service/bookings/${id}/payment`,
    BOOKING_INVOICE: (id: string) => `/service/bookings/${id}/invoice`,
    BOOKING_REVISIT: (id: string) => `/service/bookings/${id}/revisit`,
    BOOKING_REASSIGN_PRO: (id: string) => `/service/bookings/${id}/reassign-pro`,
    BOOKING_RESUME: (id: string) => `/service/bookings/${id}/resume`,
    BOOKING_GENERATE_OTP: (id: string) => `/service/bookings/${id}/generate-otp`,
    JOB_DETAIL: (id: string) => `/service/jobs/${id}`,
    JOB_PARTS_APPROVE: (id: string) => `/service/jobs/${id}/parts/approve`,
    JOB_PARTS_PLACE_ORDER: (id: string) => `/service/jobs/${id}/parts/place-order`,
    JOB_PART_APPROVE: (id: string, partId: string) => `/service/jobs/${id}/parts/${partId}/approve`,
    JOB_PART_REMOVE: (id: string, partId: string) => `/service/jobs/${id}/parts/${partId}/remove`,
    JOB_RATING: (id: string) => `/service/jobs/${id}/rating`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
  },
  MASTER: {
    CATEGORIES: '/master/categories',
    BRANDS: '/master/brands',
    RETURN_REASONS: '/master/return-reasons',
    STATES: '/master/states',
    CITIES: '/master/cities',
    ZONES: '/master/zones',
    AREAS: '/master/areas',
    PAYMENT_METHODS: '/master/payment-methods',
    ORDER_SETTINGS: '/master/order-settings',
  },
  WAREHOUSES: {
    RESOLVE: '/warehouses/resolve',
  },
  STOREFRONT: {
    LOCATION: '/storefront/location',
    PRODUCTS: '/storefront/products',
    PRODUCT_DETAIL: (id: string | number) => `/storefront/products/${id}`,
    DELIVERY_CONTEXT: '/storefront/delivery-context',
  },
} as const;
